# The Prefix for each Rank is the Prefix set in LuckPerms
# To set player color set meta tag "CustomTablistPlayerColor" followed by color code (e.g. &6) in LuckPerms

# Available Tags: %TPS%.
# You can also use the PlaceholderAPIs tags.

# To switch between texts in one line at the given refresh rate use '::' to define multiple texts.

Tablist:
  Header:
    - "example text"
    - "example info"

  Footer:
    - "example text"
    - "example info"

  RefreshRate: 3 #in Seconds

  SwitchTextsTime: 20 #in Seconds